version: '3.9'

services:
  app:
    build:
      context: .
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    container_name: serverless
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/www
